//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyMotionControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM12")]
        public string TOOLCONTROLLER_TCU_PORTNAME {
            get {
                return ((string)(this["TOOLCONTROLLER_TCU_PORTNAME"]));
            }
            set {
                this["TOOLCONTROLLER_TCU_PORTNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM7")]
        public string TOOLCONTROLLER_TRT_PORTNAME {
            get {
                return ((string)(this["TOOLCONTROLLER_TRT_PORTNAME"]));
            }
            set {
                this["TOOLCONTROLLER_TRT_PORTNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.11.50")]
        public string ROBOT_TCP_IPADDRESS {
            get {
                return ((string)(this["ROBOT_TCP_IPADDRESS"]));
            }
            set {
                this["ROBOT_TCP_IPADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string LENSPROFILE_TRT_DEFAULT {
            get {
                return ((string)(this["LENSPROFILE_TRT_DEFAULT"]));
            }
            set {
                this["LENSPROFILE_TRT_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ROBOT_RUNSTREAM_INTERVAL {
            get {
                return ((int)(this["ROBOT_RUNSTREAM_INTERVAL"]));
            }
            set {
                this["ROBOT_RUNSTREAM_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ROBOT_LIVEMOVE_INTERVAL {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_INTERVAL"]));
            }
            set {
                this["ROBOT_LIVEMOVE_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ROBOT_LIVEMOVE_STEPSIZE {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_STEPSIZE"]));
            }
            set {
                this["ROBOT_LIVEMOVE_STEPSIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ROBOT_LIVEMOVE_STEPSIZEMAX {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_STEPSIZEMAX"]));
            }
            set {
                this["ROBOT_LIVEMOVE_STEPSIZEMAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SIM_EXP1_VEL {
            get {
                return ((int)(this["SIM_EXP1_VEL"]));
            }
            set {
                this["SIM_EXP1_VEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SIM_EXP1_ACC {
            get {
                return ((int)(this["SIM_EXP1_ACC"]));
            }
            set {
                this["SIM_EXP1_ACC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SIM_EXP1_DEC {
            get {
                return ((int)(this["SIM_EXP1_DEC"]));
            }
            set {
                this["SIM_EXP1_DEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SIM_EXP1_LEAVE {
            get {
                return ((int)(this["SIM_EXP1_LEAVE"]));
            }
            set {
                this["SIM_EXP1_LEAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SIM_EXP1_REACH {
            get {
                return ((int)(this["SIM_EXP1_REACH"]));
            }
            set {
                this["SIM_EXP1_REACH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ROBOT_DEFAULT_LEAVE {
            get {
                return ((int)(this["ROBOT_DEFAULT_LEAVE"]));
            }
            set {
                this["ROBOT_DEFAULT_LEAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ROBOT_DEFAULT_REACH {
            get {
                return ((int)(this["ROBOT_DEFAULT_REACH"]));
            }
            set {
                this["ROBOT_DEFAULT_REACH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ROBOT_RUNSYNC_INTERVAL {
            get {
                return ((int)(this["ROBOT_RUNSYNC_INTERVAL"]));
            }
            set {
                this["ROBOT_RUNSYNC_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ROBOT_RUNCOMMANDS_INTERVAL {
            get {
                return ((int)(this["ROBOT_RUNCOMMANDS_INTERVAL"]));
            }
            set {
                this["ROBOT_RUNCOMMANDS_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TOOLCONTROLLER_AUTOCONNECT_TRT {
            get {
                return ((bool)(this["TOOLCONTROLLER_AUTOCONNECT_TRT"]));
            }
            set {
                this["TOOLCONTROLLER_AUTOCONNECT_TRT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TOOLCONTROLLER_AUTOCONNECT_TCU {
            get {
                return ((bool)(this["TOOLCONTROLLER_AUTOCONNECT_TCU"]));
            }
            set {
                this["TOOLCONTROLLER_AUTOCONNECT_TCU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIDEOCAPTURE_AUTOSTART {
            get {
                return ((bool)(this["VIDEOCAPTURE_AUTOSTART"]));
            }
            set {
                this["VIDEOCAPTURE_AUTOSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ROBOT_EXPORT2_INTERVAL {
            get {
                return ((int)(this["ROBOT_EXPORT2_INTERVAL"]));
            }
            set {
                this["ROBOT_EXPORT2_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ROBOT_SAFETY_VELOCITY {
            get {
                return ((int)(this["ROBOT_SAFETY_VELOCITY"]));
            }
            set {
                this["ROBOT_SAFETY_VELOCITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ROBOT_SAFETY_ACCEL {
            get {
                return ((int)(this["ROBOT_SAFETY_ACCEL"]));
            }
            set {
                this["ROBOT_SAFETY_ACCEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ROBOT_SAFETY_DECEL {
            get {
                return ((int)(this["ROBOT_SAFETY_DECEL"]));
            }
            set {
                this["ROBOT_SAFETY_DECEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TOOLCONTROLLER_FOCUS_DEADBAND {
            get {
                return ((int)(this["TOOLCONTROLLER_FOCUS_DEADBAND"]));
            }
            set {
                this["TOOLCONTROLLER_FOCUS_DEADBAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TOOLCONTROLLER_IRIS_DEADBAND {
            get {
                return ((int)(this["TOOLCONTROLLER_IRIS_DEADBAND"]));
            }
            set {
                this["TOOLCONTROLLER_IRIS_DEADBAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TOOLCONTROLLER_ZOOM_DEADBAND {
            get {
                return ((int)(this["TOOLCONTROLLER_ZOOM_DEADBAND"]));
            }
            set {
                this["TOOLCONTROLLER_ZOOM_DEADBAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TOOLCONTROLLER_AUX_DEADBAND {
            get {
                return ((int)(this["TOOLCONTROLLER_AUX_DEADBAND"]));
            }
            set {
                this["TOOLCONTROLLER_AUX_DEADBAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int TARGET_POINT_X {
            get {
                return ((int)(this["TARGET_POINT_X"]));
            }
            set {
                this["TARGET_POINT_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TARGET_POINT_Y {
            get {
                return ((int)(this["TARGET_POINT_Y"]));
            }
            set {
                this["TARGET_POINT_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550")]
        public int TARGET_POINT_Z {
            get {
                return ((int)(this["TARGET_POINT_Z"]));
            }
            set {
                this["TARGET_POINT_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SIMULATOR_SYNCFOCUS_INTERVAL {
            get {
                return ((int)(this["SIMULATOR_SYNCFOCUS_INTERVAL"]));
            }
            set {
                this["SIMULATOR_SYNCFOCUS_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ROBOT_RUNSYNC_TIMEOUT {
            get {
                return ((int)(this["ROBOT_RUNSYNC_TIMEOUT"]));
            }
            set {
                this["ROBOT_RUNSYNC_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ROBOT_TCP_FEEDBACK_SIZE {
            get {
                return ((int)(this["ROBOT_TCP_FEEDBACK_SIZE"]));
            }
            set {
                this["ROBOT_TCP_FEEDBACK_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ROBOT_TCP_PORT_MOTION {
            get {
                return ((int)(this["ROBOT_TCP_PORT_MOTION"]));
            }
            set {
                this["ROBOT_TCP_PORT_MOTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ROBOT_TCP_PORT_FEEDBACK {
            get {
                return ((int)(this["ROBOT_TCP_PORT_FEEDBACK"]));
            }
            set {
                this["ROBOT_TCP_PORT_FEEDBACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SIM_CALCTHREAD_INTERVAL {
            get {
                return ((int)(this["SIM_CALCTHREAD_INTERVAL"]));
            }
            set {
                this["SIM_CALCTHREAD_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int COUNTDOWN_DURATION {
            get {
                return ((int)(this["COUNTDOWN_DURATION"]));
            }
            set {
                this["COUNTDOWN_DURATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string RANGEFINDER_PORTNAME {
            get {
                return ((string)(this["RANGEFINDER_PORTNAME"]));
            }
            set {
                this["RANGEFINDER_PORTNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RANGEFINDER_AUTOCONNECT {
            get {
                return ((bool)(this["RANGEFINDER_AUTOCONNECT"]));
            }
            set {
                this["RANGEFINDER_AUTOCONNECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RANGEFINDER_REFRESHRATE {
            get {
                return ((int)(this["RANGEFINDER_REFRESHRATE"]));
            }
            set {
                this["RANGEFINDER_REFRESHRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAMERA_SYNC {
            get {
                return ((bool)(this["CAMERA_SYNC"]));
            }
            set {
                this["CAMERA_SYNC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int RUN_SYNC_DELAY {
            get {
                return ((int)(this["RUN_SYNC_DELAY"]));
            }
            set {
                this["RUN_SYNC_DELAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PHANTOM_REFRESH_INTERVAL {
            get {
                return ((int)(this["PHANTOM_REFRESH_INTERVAL"]));
            }
            set {
                this["PHANTOM_REFRESH_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double DURATION {
            get {
                return ((double)(this["DURATION"]));
            }
            set {
                this["DURATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COUNTDOWN_ALERT {
            get {
                return ((bool)(this["COUNTDOWN_ALERT"]));
            }
            set {
                this["COUNTDOWN_ALERT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ROBOT_LIVEMOVE_TRACKING_STEPSIZE {
            get {
                return ((double)(this["ROBOT_LIVEMOVE_TRACKING_STEPSIZE"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_STEPSIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ROBOT_LIVEMOVE_TRACKING_STEPSIZEMAX {
            get {
                return ((double)(this["ROBOT_LIVEMOVE_TRACKING_STEPSIZEMAX"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_STEPSIZEMAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ROBOT_LIVEMOVE_TRACKING_INTERVAL {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_TRACKING_INTERVAL"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string CAMERA_RED_PORTNAME {
            get {
                return ((string)(this["CAMERA_RED_PORTNAME"]));
            }
            set {
                this["CAMERA_RED_PORTNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CAMERA_RED_REFRESHRATE {
            get {
                return ((int)(this["CAMERA_RED_REFRESHRATE"]));
            }
            set {
                this["CAMERA_RED_REFRESHRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAMERA_RED_AUTOCONNECT {
            get {
                return ((bool)(this["CAMERA_RED_AUTOCONNECT"]));
            }
            set {
                this["CAMERA_RED_AUTOCONNECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ROBOT_DEFAULT_ACC {
            get {
                return ((int)(this["ROBOT_DEFAULT_ACC"]));
            }
            set {
                this["ROBOT_DEFAULT_ACC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ROBOT_DEFAULT_DEC {
            get {
                return ((int)(this["ROBOT_DEFAULT_DEC"]));
            }
            set {
                this["ROBOT_DEFAULT_DEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ROBOT_DEFAULT_VEL {
            get {
                return ((int)(this["ROBOT_DEFAULT_VEL"]));
            }
            set {
                this["ROBOT_DEFAULT_VEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ROBOT_CMDMODE_REHEARSE_AUTOFOCUS {
            get {
                return ((bool)(this["ROBOT_CMDMODE_REHEARSE_AUTOFOCUS"]));
            }
            set {
                this["ROBOT_CMDMODE_REHEARSE_AUTOFOCUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAMERA_AUTOSAVE_FOOTAGE {
            get {
                return ((bool)(this["CAMERA_AUTOSAVE_FOOTAGE"]));
            }
            set {
                this["CAMERA_AUTOSAVE_FOOTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public double TOOLCONTROLLER_FOCUS_POSITION_DEFAULT {
            get {
                return ((double)(this["TOOLCONTROLLER_FOCUS_POSITION_DEFAULT"]));
            }
            set {
                this["TOOLCONTROLLER_FOCUS_POSITION_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CAMERA_BOTTOM_OFFSET_X {
            get {
                return ((float)(this["CAMERA_BOTTOM_OFFSET_X"]));
            }
            set {
                this["CAMERA_BOTTOM_OFFSET_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CAMERA_BOTTOM_OFFSET_Y {
            get {
                return ((float)(this["CAMERA_BOTTOM_OFFSET_Y"]));
            }
            set {
                this["CAMERA_BOTTOM_OFFSET_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public float CAMERA_BOTTOM_OFFSET_Z {
            get {
                return ((float)(this["CAMERA_BOTTOM_OFFSET_Z"]));
            }
            set {
                this["CAMERA_BOTTOM_OFFSET_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CAMERA_FRONT_OFFSET_X {
            get {
                return ((float)(this["CAMERA_FRONT_OFFSET_X"]));
            }
            set {
                this["CAMERA_FRONT_OFFSET_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CAMERA_FRONT_OFFSET_Y {
            get {
                return ((float)(this["CAMERA_FRONT_OFFSET_Y"]));
            }
            set {
                this["CAMERA_FRONT_OFFSET_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float CAMERA_FRONT_OFFSET_Z {
            get {
                return ((float)(this["CAMERA_FRONT_OFFSET_Z"]));
            }
            set {
                this["CAMERA_FRONT_OFFSET_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAMERA_AUTOSTOP_RECORDING {
            get {
                return ((bool)(this["CAMERA_AUTOSTOP_RECORDING"]));
            }
            set {
                this["CAMERA_AUTOSTOP_RECORDING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAMERA_STOP_RECORDING_DELAY {
            get {
                return ((int)(this["CAMERA_STOP_RECORDING_DELAY"]));
            }
            set {
                this["CAMERA_STOP_RECORDING_DELAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ROBOT_LIVEMOVE_TRACKING_LEAVE {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_TRACKING_LEAVE"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_LEAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ROBOT_LIVEMOVE_TRACKING_REACH {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_TRACKING_REACH"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_REACH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ROBOT_LIVEMOVE_TRACKING_VEL {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_TRACKING_VEL"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_VEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ROBOT_LIVEMOVE_TRACKING_ACCEL {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_TRACKING_ACCEL"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_ACCEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ROBOT_LIVEMOVE_TRACKING_DECEL {
            get {
                return ((int)(this["ROBOT_LIVEMOVE_TRACKING_DECEL"]));
            }
            set {
                this["ROBOT_LIVEMOVE_TRACKING_DECEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VIDEOCAPTURE_SELECTED {
            get {
                return ((int)(this["VIDEOCAPTURE_SELECTED"]));
            }
            set {
                this["VIDEOCAPTURE_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NA")]
        public string VIDEOCAPTURE_SELECTED_NAME {
            get {
                return ((string)(this["VIDEOCAPTURE_SELECTED_NAME"]));
            }
            set {
                this["VIDEOCAPTURE_SELECTED_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ROBOT_START_DELAY {
            get {
                return ((int)(this["ROBOT_START_DELAY"]));
            }
            set {
                this["ROBOT_START_DELAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAMERA_SELECTED_INDEX {
            get {
                return ((int)(this["CAMERA_SELECTED_INDEX"]));
            }
            set {
                this["CAMERA_SELECTED_INDEX"] = value;
            }
        }
    }
}
